on:
    workflow_dispatch:
      inputs:
        version:
          description: "The version used for the release asset."
          required: true
  
name: Build
jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run:  GOARCH=arm64 make cloudflared
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload darwin artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cloudflared
        asset_name: cloudflared-darwin-arm64
        asset_content_type: application/binary